# example values

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru

server:
  port: 8080

spring:
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: 1111
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true